backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

# media_folder: "static/img" # Media files will be stored in the repo under images/uploads
media_folder: "static/img" 
public_folder: "/images/uploads"

collections:
 # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Modified Date", name: "modified_date", widget: "datetime" }
      - { label: "Description/Summary", name: "description", widget: "text" , required: false}
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Navigation Title", name: "navtitle", widget: "string" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "nav" }
      - { label: "Article Image", name: "article_image", widget: "image" , required: false}
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - { label: "Body", name: "body", widget: "markdown" , required: false}
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Modified Date", name: "modified_date", widget: "datetime" }
      - { label: "Description/Summary", name: "description", widget: "text"}
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Article Image", name: "article_image", widget: "image" , required: false}
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - { label: "Body", name: "body", widget: "markdown" }
   # Our komunitas posts
  - name: "komunitas" # Used in routes, e.g., /admin/collections/blog
    label: "Komunitas" # Used in the UI
    folder: "komunitas" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Modified Date", name: "modified_date", widget: "datetime" }
      - { label: "Description/Summary", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["komunitas"] }
      - { label: "Article Image", name: "article_image", widget: "image" , required: false}
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - { label: "Body", name: "body", widget: "markdown" }      
  # Our tips posts
  - name: "tips" # Used in routes, e.g., /admin/collections/blog
    label: "Tips" # Used in the UI
    folder: "tips" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Modified Date", name: "modified_date", widget: "datetime" }
      - { label: "Description/Summary", name: "description", widget: "text"}
      - { label: "Tags", name: "tags", widget: "list", default: ["tips"] }
      - { label: "Article Image", name: "article_image", widget: "image" , required: false}
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - { label: "Body", name: "body", widget: "markdown" } 
  # Our game posts
  - name: "game" # Used in routes, e.g., /admin/collections/blog
    label: "Game" # Used in the UI
    folder: "game" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Modified Date", name: "modified_date", widget: "datetime" }
      - { label: "Description/Summary", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["game"] }
      - { label: "Article Image", name: "article_image", widget: "image" , required: false}
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - { label: "Body", name: "body", widget: "markdown" }          
# Our game posts
  - name: "profil" # Used in routes, e.g., /admin/collections/blog
    label: "Profil" # Used in the UI
    folder: "profil" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Modified Date", name: "modified_date", widget: "datetime" }
      - { label: "Description/Summary", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["profil"] }
      - { label: "Article Image", name: "article_image", widget: "image" , required: false}
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - { label: "Body", name: "body", widget: "markdown" } 